[fix #136] modify dockerfile
wunder3605/iri pull request #144
Opened 2019-02-21 01:58 UTC by wangyh2016

modify the dockerfile

2019-02-21 02:03 UTC, stplaydog requested changes

2019-02-21 02:03 UTC, stplaydog commented on scripts/Dockerfile
> +RUN ipfs init
init 和 daemon就不要放在dockerfile里了

2019-02-21 02:03 UTC, stplaydog commented on scripts/Dockerfile
> +RUN chmod +x docker-entrypoint.sh
把 docker-entrypoint.sh 也上传吧。

2019-02-21 02:12 UTC, stplaydog commented on scripts/docker-entrypoint.sh
> +source /venv/bin/activate
删掉这一行试一试。

2019-02-21 02:12 UTC, stplaydog commented on scripts/docker-entrypoint.sh
> +#
多余的注释。

2019-02-21 09:38 UTC, wangyh2016 commented on scripts/docker-entrypoint.sh
> +source /venv/bin/activate
好的

2019-02-21 09:39 UTC, wangyh2016 commented on scripts/docker-entrypoint.sh
> +#
已删除

2019-02-25 02:01 UTC, stplaydog approved these changes

2019-02-25 02:03 UTC, merged

2019-02-26 04:12 UTC, knightlf commented
1. IPFS 初始化之后没有改变节点，存储的文件，会到外网的节点之中
2. 基础镜像建议使用可控的BASE版本，或者咱们私有的HUB来建立，不建议使用python:2.7
3. IOTA API 使用本地的配置，建议挂载到宿主启动
4. pip安装包，建议使用requment安装， 并收集到内网版本库安装，或者在基础镜像中预置
5. 多进程的阻塞，建议状态汇总一下，如果实际情况有特殊需求，可使用supervisor来控制并行启动