fix dockerfile bug
wunder3605/iri pull request #206
Opened 2019-03-15 07:50 UTC by wangyh2016

fix dockerfile bug 
--delete ipfs info in dockerfile 
--get container Intranet IP mapping

2019-03-16 00:22 UTC, stplaydog requested changes

2019-03-16 00:22 UTC, stplaydog commented on scripts/iota_api/ipinfo.txt
> +140.143.187.24,172.21.0.26
please do not place this ip info

2019-03-18 02:24 UTC, wangyh2016 commented on scripts/iota_api/ipinfo.txt
> +140.143.187.24,172.21.0.26
Ok, I will delete this file.

2019-03-18 02:27 UTC, stplaydog approved these changes

2019-03-18 07:14 UTC, stplaydog approved these changes

2019-03-18 07:14 UTC, stplaydog commented on scripts/iota_api/modify_conf_file.py
> +    oret = subprocess.Popen("curl ifconfig.io",shell=True,stdout=subprocess.PIPE).stdout
need an ip list, might have security issues.

2019-03-19 07:14 UTC, merged